config/routes.rb
Rails.application.routes.draw do
  root to: 'polls#index'
  get 'pages/welcome'
  devise_for :users

  resources :polls do
    resources :poll_items, only: [:create] do
      resource :vote, module: :polls
    end
  end

  get 'welcome', to: 'pages#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
    belongs_to :user

    has_many :poll_items, dependent: :destroy

    accepts_nested_attributes_for :poll_items, reject_if: :all_blank, allow_destroy: true

    has_one_attached :image
    has_rich_text :description
end

app/models/poll_item.rb
class PollItem < ApplicationRecord
  belongs_to :poll

  has_one_attached :image

  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :polls, dependent: :destroy

  has_many :votes, dependent: :destroy

  def votes?(poll_item)
    poll_item.votes.where(user_id: id).any?
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :user
    belongs_to :poll_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/polls/votes_controller.rb
class Polls::VotesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_poll
    before_action :set_poll_item

    def create
        @poll_item.votes.where(user_id: current_user.id).first_or_create

        respond_to do |format|
            format.html { redirect_to @poll }
            format.js
        end
    end

    def destroy
        @poll_item.votes.where(user_id: current_user.id).destroy_all

        respond_to do |format|
            format.html { redirect_to @poll }
            format.js
        end
    end

    private

    def set_poll
        @poll = Poll.find(params[:poll_id])
    end

    def set_poll_item
        @poll_item = PollItem.find(params[:poll_item_id])
    end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: %i[ show edit update destroy ]

  def index
    @polls = Poll.all
  end

  def show
  end

  def new
    @poll = current_user.polls.build
  end

  def edit
  end

  def create
    @poll = current_user.polls.build(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: "Poll was successfully created." }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: "Poll was successfully updated." }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: "Poll was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:title, :description, :image, poll_items_attributes:[:id, :name, :description, :image, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polling</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/polls/_form.html.erb
<%= form_with(model: poll) do |form| %>
  <% if poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
        <% poll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <h3>Add Poll Items</h3>
  <%= form.fields_for :poll_items do |poll_item| %>
    <%= render 'poll_item_fields', f: poll_item %>
  <% end %>
    
  <div class="links">
    <%= link_to_add_association "Add Item", form, :poll_items %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/polls/_poll_item_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div class="field">
        <%= link_to_remove_association "Remove item", f %>
    </div>
</div>

app/views/polls/_votes.html.erb
<% if user_signed_in? && Vote.where(user_id: current_user.id, poll_item_id: @poll_item.id).count > 0 %>
    <p>You have voted</p>
    <%= link_to "Unvote", poll_poll_item_vote_path(@poll, @poll_item), method: :delete %>
<% else %>
    <%= link_to "Vote", poll_poll_item_vote_path(@poll, @poll_item), method: :post %>
<% end %>

<%# if Vote.where(user_id: current_user.id).where(poll_item_id: @poll.poll_items.pluck(:id)).count > 0 %>
<%# if user_signed_in? && current_user.votes?(@poll_item) %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polls</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.title %></td>
        <td><%= poll.description %></td>
        <td><%= poll.user_id %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poll.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @poll.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @poll.user.email %>
</p>

<h3>Poll Items</h3>
<ul>
  <% for @poll_item in @poll.poll_items %>
    <li><%= @poll_item.name %>(<%= @poll_item.description %>)</li>
    <div id="votes">
      <%= render partial: "votes" %>
    </div>
  <% end %>
</ul>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/polls/votes/create.js.erb
$("#votes").html("<%=j render partial: "polls/votes" %>");

app/views/polls/votes/destroy.js.erb
$("#votes").html("<%=j render partial: "polls/votes" %>");